In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np
import plotly as plt

In [6]:
data=pd.read_csv(r"james_bond_data.csv")

In [7]:
data.head(10)

,Release,Movie,Bond,Bond_Car_MFG,US_Gross,World_Gross,Budget_Movie,Film_Length,Avg_User_IMDB,Avg_User_Rtn_Tom,Martinis,Kills_Bond
0,"June, 1962",Dr. No,Sean Connery,Sunbeam,"$16,067,035.00","$59,567,035.00","$1,000.00",110 mins,7.3,7.7,2,4
1,"August, 1963",From Russia with Love,Sean Connery,Bentley,"$24,800,000.00","$78,900,000.00","$2,000.00",115 mins,7.5,8.0,0,11
2,"May, 1964",Goldfinger,Sean Connery,Aston Martin,"$51,100,000.00","$124,900,000.00","$3,000.00",110 mins,7.8,8.4,1,9
3,"September, 1965",Thunderball,Sean Connery,Aston Martin,"$63,600,000.00","$141,200,000.00","$9,000.00",130 mins,7.0,6.8,0,20
4,"November, 1967",You Only Live Twice,Sean Connery,Toyota,"$43,100,000.00","$111,600,000.00","$9,500.00",117 mins,6.9,6.3,1,21
5,"July, 1969",On Her Majesty's Secret Service,George Lazenby,Mercury,"$22,800,000.00","$82,000,000.00","$8,000.00",142 mins,6.8,6.7,1,5
6,"March, 1971",Diamonds Are Forever,Shawn Connery,Ford,"$43,800,000.00","$116,000,000.00","$7,200.00",1200 mins,6.7,6.3,0,7
7,"August, 1973",Live and Let Die,Roger Moore,AMC,"$35,400,000.00","$161,800,000.00","$7,000.00",121 mins,6.8,5.9,0,8
8,"July, 1974",The Man with the Golden Gun,Roger Moore,AMC,"$21,000,000.00","$97,600,000.00","$7,000.00",125 mins,6.7,5.1,0,1
9,"July, 1974",The Man with the Golden Gun,Roger Moore,AMC,"$21,000,000.00","$97,600,000.00","$7,000.00",125 mins,6.7,5.1,0,1

In [8]:
data.tail(8)

,Release,Movie,Bond,Bond_Car_MFG,US_Gross,World_Gross,Budget_Movie,Film_Length,Avg_User_IMDB,Avg_User_Rtn_Tom,Martinis,Kills_Bond
19,"July, 1997",Tomorrow Never Dies,Pierce Brosnan,Aston Martin,"$125,304,276.00","$339,504,276.00","$110,000.00",119 mins,6.4,6.0,1,30
20,"June, 1999",The World Is Not Enough,Pierce Brosnan,BMW,"$126,930,660.00","$361,730,660.00","$135,000.00",128 mins,6.3,5.7,1,27
21,"August, 2002",Die Another Day,Pierce Brosnan,Aston Martin,"$160,942,139.00","$431,942,139.00","$142,000.00",133 mins,6.0,6.1,2,31
22,"February, 2006",Casino Royale,Daniel Craig,Astin Martin,"$167,365,000.00","$596,365,000.00","$102,000.00",144 mins,7.9,7.8,3,11
23,"December, 2008",Quantum of Solace,Daniel Craig,Aston Martin,"$169,368,427.00","$591,692,078.00","$230,000.00",106 mins,6.7,6.1,-6,16
24,"November, 2012",Skyfall,Daniel Craig,Astin Martin,"$304,360,277.00","$1,108,561,108.00","$200,000.00",143 mins,7.8,8.2,1,26
25,"September, 2015",Spectre,Daniel Craig,Aston Martin,"$200,074,175.00","$879,620,923.00","$245,000.00",148 mins,6.8,6.4,1,30
26,"November, 2021",No Time to Die,Daniel Craig,Aston Martin,"$160,891,007.00","$759,959,662.00","$275,000.00",163 mins,7.3,7.3,1,14

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Release           27 non-null     object
 1   Movie             27 non-null     object
 2   Bond              27 non-null     object
 3   Bond_Car_MFG      27 non-null     object
 4   US_Gross          27 non-null     object
 5   World_Gross       27 non-null     object
 6   Budget_Movie      27 non-null     object
 7   Film_Length       27 non-null     object
 8   Avg_User_IMDB     26 non-null     float64
 9   Avg_User_Rtn_Tom  26 non-null     float64
 10  Martinis          27 non-null     int64
 11  Kills_Bond        27 non-null     int64
dtypes: float64(2), int64(2), object(8)
memory usage: 2.7+ KB

AttributeError: 'function' object has no attribute 'combine_first'

In [10]:
print(data.to_string())

            Release                            Movie            Bond  Bond_Car_MFG          US_Gross         World_Gross  Budget_Movie Film_Length  Avg_User_IMDB  Avg_User_Rtn_Tom  Martinis  Kills_Bond
0        June, 1962                           Dr. No    Sean Connery       Sunbeam   $16,067,035.00      $59,567,035.00     $1,000.00     110 mins            7.3               7.7         2           4
1      August, 1963            From Russia with Love    Sean Connery       Bentley   $24,800,000.00      $78,900,000.00     $2,000.00     115 mins            7.5               8.0         0          11
2         May, 1964                       Goldfinger    Sean Connery  Aston Martin   $51,100,000.00     $124,900,000.00     $3,000.00     110 mins            7.8               8.4         1           9
3   September, 1965                      Thunderball    Sean Connery  Aston Martin   $63,600,000.00     $141,200,000.00     $9,000.00     130 mins            7.0               6.8         0          20
4    November, 1967              You Only Live Twice    Sean Connery        Toyota   $43,100,000.00     $111,600,000.00     $9,500.00     117 mins            6.9               6.3         1          21
5        July, 1969  On Her Majesty's Secret Service  George Lazenby       Mercury   $22,800,000.00      $82,000,000.00     $8,000.00     142 mins            6.8               6.7         1           5
6       March, 1971             Diamonds Are Forever   Shawn Connery          Ford   $43,800,000.00     $116,000,000.00     $7,200.00    1200 mins            6.7               6.3         0           7
7      August, 1973                 Live and Let Die     Roger Moore           AMC   $35,400,000.00     $161,800,000.00     $7,000.00     121 mins            6.8               5.9         0           8
8        July, 1974      The Man with the Golden Gun     Roger Moore           AMC   $21,000,000.00      $97,600,000.00     $7,000.00     125 mins            6.7               5.1         0           1
9        July, 1974      The Man with the Golden Gun     Roger Moore           AMC   $21,000,000.00      $97,600,000.00     $7,000.00     125 mins            6.7               5.1         0           1
10      April, 1977             The Spy Who Loved Me     Roger Moore         Lotus   $46,800,000.00     $185,400,000.00    $14,000.00     125 mins            NaN               NaN         1          31
11    October, 1979                        Moonraker     Roger Moore         Lotus   $70,300,000.00     $210,300,000.00    $31,000.00     126 mins            6.2               5.7         1          12
12       June, 1981               For Your Eyes Only     Roger MOORE       Citroen   $54,800,000.00     $195,300,000.00    $28,000.00     127 mins            6.8               6.3         0          18
13      March, 1983                        Octopussy     Roger Moore         Bajaj   $67,900,000.00     $187,500,000.00    $27,500.00     131 mins            6.5               5.3         0          15
14    October, 1985                 A View to a Kill     Roger Moore   Rolls Royce   $50,327,960.00     $152,627,960.00    $30,000.00     131 mins            6.2               4.7         0           5
15        May, 1987             The Living Daylights  Timothy Dalton   Rolls Royce   $51,185,000.00     $191,200,000.00    $40,000.00     130 mins            6.7               6.3         2          13
16        May, 1987             The Living Daylights  Timothy Dalton   Rolls Royce   $51,185,000.00     $191,200,000.00    $40,000.00     130 mins            6.7               6.3         2          13
17    January, 1989                  License to Kill  Timothy Dalton  Aston Martin   $34,667,015.00     $156,167,015.00    $42,000.00     133 mins            6.5               6.0         1          10
18  September, 1995                        GoldenEye  Pierce Brosnan           BMW  $106,429,941.00     $356,429,941.00    $60,000.00     130 mins            7.2               6.9         1          47
19       July, 1997              Tomorrow Never Dies  Pierce Brosnan  Aston Martin  $125,304,276.00     $339,504,276.00   $110,000.00     119 mins            6.4               6.0         1          30
20       June, 1999          The World Is Not Enough  Pierce Brosnan           BMW  $126,930,660.00     $361,730,660.00   $135,000.00     128 mins            6.3               5.7         1          27
21     August, 2002                  Die Another Day  Pierce Brosnan  Aston Martin  $160,942,139.00     $431,942,139.00   $142,000.00     133 mins            6.0               6.1         2          31
22   February, 2006                    Casino Royale    Daniel Craig  Astin Martin  $167,365,000.00     $596,365,000.00   $102,000.00     144 mins            7.9               7.8         3          11
23   December, 2008                Quantum of Solace    Daniel Craig  Aston Martin  $169,368,427.00     $591,692,078.00   $230,000.00     106 mins            6.7               6.1        -6          16
24   November, 2012                          Skyfall    Daniel Craig  Astin Martin  $304,360,277.00   $1,108,561,108.00   $200,000.00     143 mins            7.8               8.2         1          26
25  September, 2015                          Spectre    Daniel Craig  Aston Martin  $200,074,175.00     $879,620,923.00   $245,000.00     148 mins            6.8               6.4         1          30
26   November, 2021                   No Time to Die    Daniel Craig  Aston Martin  $160,891,007.00     $759,959,662.00   $275,000.00     163 mins            7.3               7.3         1          14

In [37]:
data= (
data.rename(columns= new_columns_names).combine_first(
pd.DataFrame ({"Avg_User_IMDB":{10:7.1},"Avg_user_Rtn_Tom":{10:6.8}})
)
.assign( 
    World_Gross=lambda data:(
data["World_Gross"]
.replace("[$,],","",regex=T)
.astype("float64")
)))
data.head()

NameError: name 'new_columns_names' is not defined

In [38]:
data=data.rename(column=new_column)
data.column

NameError: name 'new_column' is not defined

In [39]:
data["Martinis"].describe()

count    27.000000
mean      0.629630
std       1.547905
min      -6.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       3.000000
Name: Martinis, dtype: float64

In [43]:
data["Martinis"]=data["Martinis"].fillna(data["Martinis"].mean())

In [46]:
data.loc[data.isna().any(axis="columns")]
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Release           27 non-null     object
 1   Movie             27 non-null     object
 2   Bond              27 non-null     object
 3   Bond_Car_MFG      27 non-null     object
 4   US_Gross          27 non-null     object
 5   World_Gross       27 non-null     object
 6   Budget_Movie      27 non-null     object
 7   Film_Length       27 non-null     object
 8   Avg_User_IMDB     26 non-null     float64
 9   Avg_User_Rtn_Tom  26 non-null     float64
 10  Martinis          27 non-null     int64
 11  Kills_Bond        27 non-null     int64
dtypes: float64(2), int64(2), object(8)
memory usage: 2.7+ KB

In [47]:
data.isnull().sum()

Release             0
Movie               0
Bond                0
Bond_Car_MFG        0
US_Gross            0
World_Gross         0
Budget_Movie        0
Film_Length         0
Avg_User_IMDB       1
Avg_User_Rtn_Tom    1
Martinis            0
Kills_Bond          0
dtype: int64

In [50]:
data["Avg_User_IMDB "] =data["Avg_User_IMDB "].fillna(data["Avg_User_IMDB "].median())
 data["Avg_User_Rtn_Tom  "]=data["Avg_User_Rtn_Tom  "].fillna(data[" Avg_User_Rtn_Tom "].median())
data.isnull().sum()

IndentationError: unexpected indent (761646042.py, line 2)

In [1]:
git init

SyntaxError: invalid syntax (2830201818.py, line 1)